// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKa6Y8xPK0b83PamaRysL_TOAf5xeg6bw',
    appId: '1:608122388695:web:02e1c054c2eb1fe0837092',
    messagingSenderId: '608122388695',
    projectId: 'kkatalk-24148',
    authDomain: 'kkatalk-24148.firebaseapp.com',
    storageBucket: 'kkatalk-24148.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD92v7H8QvGs8bSLn65dew9RYt7fq7fMwU',
    appId: '1:608122388695:android:22e0f157f27926f7837092',
    messagingSenderId: '608122388695',
    projectId: 'kkatalk-24148',
    storageBucket: 'kkatalk-24148.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB71S4xNMecvOyysHYY7fsam2p_Wd6wDZE',
    appId: '1:608122388695:ios:092aaec8891e18dd837092',
    messagingSenderId: '608122388695',
    projectId: 'kkatalk-24148',
    storageBucket: 'kkatalk-24148.appspot.com',
    iosBundleId: 'com.example.team3Kakao',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB71S4xNMecvOyysHYY7fsam2p_Wd6wDZE',
    appId: '1:608122388695:ios:083f3d8b46fce222837092',
    messagingSenderId: '608122388695',
    projectId: 'kkatalk-24148',
    storageBucket: 'kkatalk-24148.appspot.com',
    iosBundleId: 'com.example.team3Kakao.RunnerTests',
  );
}
